name: Build All

on: [ workflow_call, workflow_dispatch ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build
        env:
          KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGN_KEY: ${{ secrets.KEY_ALIAS }}
          SIGN_PASS: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          echo $KEYSTORE | base64 --decode > keystore.jks
          ./gradlew app:assembleRelease

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: app/build/outputs/apk/release/*.apk
          retention-days: 1

  verify-uploaded-builds:
    needs:
      - build-android
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifacts
        uses: actions/download-artifact@v4

      - name: Print all files
        run: ls -R